        <div class="off-canvas-absolute position-top" id="menu-off-canvas" data-off-canvas>
          <ul class="vertical menu">
            <a href="/">HOME</a>
            <a href="/manifesto.html">MANIFESTO</a>
            <a href="#">BLOG</a>
          </ul>
          <button class="close-button" aria-label="Close menu" type="button" data-close>
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="grid-container">
          <div class="grid-x">
            <svg width="50" height="25" data-toggle="menu-off-canvas">
              <rect x="0" y="0" rx="2" ry="2" width="30" height="5" style="fill:white;" />
              <rect x="0" y="10" rx="2" ry="2" width="30" height="5" style="fill:white;" />
              <rect x="0" y="20" rx="2" ry="2" width="30" height="5" style="fill:white;" />
            </svg>
          </div>
        </div>
